[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nomadz_core = "8yWrExW5JBiiLC9HweTqudzvo4fRDMc4FCNSKChz6tGd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kalyonekenobe/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
