[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nomadz_core = "818jhPG7nGagquKwx1cfpiX3M68TxnGwgw2KP3rE3Rd8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kalyonekenobe/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
