[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
<<<<<<< HEAD
nomadz_core = "Fj9Xo9jE9wLv5NbhMMVvJy4S7xGKtgRmuBN8JYic3ary"
=======
nomadz_core = "GNHzqEayUCiZxuyJYMQztQ5Rc5xDNbQ611Hi5TK6Eq7T"
>>>>>>> 158bd69 (fix: referral percentages)

[registry]
url = "https://api.apr.dev"

[provider]
<<<<<<< HEAD
cluster = "Devnet"
wallet = "/Users/kalyonekenobe/.config/solana/id.json"
=======
cluster = "Localnet"
wallet = "/Users/petroyaremenko/.config/solana/id.json"
>>>>>>> 158bd69 (fix: referral percentages)

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pipeline.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
