[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nomadz_core = "7HyBnvbLHyXBZkFLFe3F8mrHsCurAqSFDzEcGfgw7yo7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "deploy.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pipeline.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "http://localhost:8899"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "CoREENxT6tW1HoK8ypY1SxRMZTcVPm7R94rH4PZNhX7d"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
