[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
nomadz_core = "GR9vV91P5kEvi9qvvBV2Cgirk4jeCkTHabbberzg8UVo"

[programs.localnet]
nomadz_core = "GR9vV91P5kEvi9qvvBV2Cgirk4jeCkTHabbberzg8UVo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/kalyonekenobe/.config/solana/id.json"

[scripts]
test = "yarn ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
